fixtures:
  repositories:
    stdlib:
      repo: git://github.com/puppetlabs/puppetlabs-stdlib.git
      ref: 4.24.0
    inifile:
      repo: git://github.com/puppetlabs/puppetlabs-inifile.git
    augeasproviders_core:
      repo: git://github.com/hercules-team/augeasproviders_core.git
    augeasproviders_shellvar:
      repo: git://github.com/hercules-team/augeasproviders_shellvar.git
  symlinks:
    yum_cron: "#{source_dir}"
