---
.gitlab-ci.yml:
  delete: true
appveyor.yml:
  delete: true
.rubocop.yml:
  profiles:
    strict:
      configs:
        RSpec/RepeatedDescription:
          Enabled: false
        RSpec/LeakyConstantDeclaration:
          Enabled: false
spec/acceptance/nodesets/debian-9.yml:
  delete: true
spec/acceptance/nodesets/debian-10.yml:
  delete: true
spec/acceptance/nodesets/debian-11.yml:
  delete: true
spec/acceptance/nodesets/ubuntu-1604.yml:
  delete: true
spec/acceptance/nodesets/ubuntu-1804.yml:
  delete: true
spec/acceptance/nodesets/ubuntu-2004.yml:
  delete: true
spec/acceptance/nodesets/ubuntu-2204.yml:
  delete: true
