name    'treydock-yum_cron'
version '0.0.1'
source 'git://github.com/treydock/puppet-yum_cron.git'
author 'treydock'
license 'Apache License, Version 2.0'
summary 'yum-cron module'
description 'yum-cron module'
project_page 'http://github.com/treydock/puppet-yum_cron'
dependency 'puppetlabs/stdlib'
dependency 'domcleal/augeasproviders'